apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vaultsecrets.maupu.org
spec:
  group: maupu.org
  names:
    kind: VaultSecret
    listKind: VaultSecretList
    plural: vaultsecrets
    singular: vaultsecret
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: VaultSecret is the Schema for the vaultsecrets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VaultSecretSpec defines the desired state of VaultSecret
          properties:
            config:
              description: Configuration part of a vault-secret object
              properties:
                addr:
                  type: string
                auth:
                  description: Mean of authentication for Vault
                  properties:
                    approle:
                      description: AppRole authentication type
                      properties:
                        name:
                          type: string
                        roleId:
                          type: string
                        secretId:
                          type: string
                      required:
                      - roleId
                      - secretId
                      type: object
                    kubernetes:
                      description: Kubernetes authentication type
                      properties:
                        cluster:
                          type: string
                        role:
                          type: string
                      required:
                      - cluster
                      - role
                      type: object
                    token:
                      type: string
                  type: object
                insecure:
                  type: boolean
                namespace:
                  type: string
              required:
              - addr
              - auth
              type: object
            secretLabels:
              additionalProperties:
                type: string
              type: object
            secretName:
              type: string
            secretType:
              type: string
            secrets:
              items:
                description: Define secrets to create from Vault
                properties:
                  field:
                    description: Field to retrieve from the path
                    type: string
                  kvPath:
                    description: Path of the key-value storage
                    type: string
                  path:
                    description: Path of the vault secret
                    type: string
                  secretKey:
                    description: Key name in the secret to create
                    type: string
                required:
                - field
                - kvPath
                - path
                - secretKey
                type: object
              type: array
            syncPeriod:
              type: string
          required:
          - config
          - secrets
          type: object
        status:
          description: Status field regarding last custom resource process
          properties:
            entries:
              items:
                description: Entry for the status field
                properties:
                  message:
                    type: string
                  rootError:
                    type: string
                  secret:
                    description: Define secrets to create from Vault
                    properties:
                      field:
                        description: Field to retrieve from the path
                        type: string
                      kvPath:
                        description: Path of the key-value storage
                        type: string
                      path:
                        description: Path of the vault secret
                        type: string
                      secretKey:
                        description: Key name in the secret to create
                        type: string
                    required:
                    - field
                    - kvPath
                    - path
                    - secretKey
                    type: object
                  status:
                    type: boolean
                required:
                - secret
                - status
                type: object
              type: array
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
